name = "ParseUnparseWKTCRS"
uuid = "5a5013b1-a58c-4d1b-bc41-ccdd1e5ea2d5"
authors = ["Neven Sajko <s@purelymail.com> and contributors"]
version = "1.1.0"

[deps]
ParseUnparse = "caaa8bb7-a042-43a4-a1c9-7594415e1478"

[compat]
ParseUnparse = "1"
julia = "1.9"
